### ISSUE TITLE
WebRTC/ORTC?

### ISSUE THREAD

**Issue by norzak** [udevbe/greenfield#1]
Hi, I was wondering how you utilize WebRTC/ORTC? are you streaming composited screen image to browser thru WebRTC/ORTC?

**Comment by Zubnix** [comment]
No, each individual application will have it's raw content live encoded on the server to a h264 frame, after which it's send using it's own dedicated webrtc datachannel, which is configured to use UDP. On reception in the browser, the h264 frame is decoded using a wasm h264 decoder, and drawn in it's own dedicated application canvas. As such the entire 'composited' image you see in the browser is created in the browser itself using ordinary dom elements.
