### ISSUE TITLE
westfield-endpoint-generator: not found

### ISSUE THREAD

**Issue by Zubnix** [udevbe/greenfield#10]
It's a fresh install of Debian 9. Having problems on install now...

Looks like westfield isn't found or something:

> **frink@dev:~/Work/greenfield/app-endpoint-server$ npm install**
> app-endpointd@1.0.0 prepare /home/rg/Work/greenfield/app-endpoint-server
> mkdir -p src/protocol/ && npm run prepare:generate:wayland && npm run prepare:generate:xdgshell
> app-endpointd@1.0.0 prepare:generate:wayland /home/rg/Work/greenfield/app-endpoint-server
> westfield-endpoint-generator ../protocol/wayland.xml -o src/protocol
> **sh: 1: westfield-endpoint-generator: not found**

_Originally posted by @frink in https://github.com/udevbe/greenfield/issues/8#issuecomment-496034336_

**Comment by Zubnix** [comment]
Normally dev dependency exectuables are automatically picked up by npm. You should see the executable in `app-endpoint-server/node-modules/.bin`. If you do and they're not picked up by npm itself, I assume there is an issue with your node.js installation(?).

The quickfix for now is use something like [nvm](https://github.com/nvm-sh/nvm) which works without issues here. I believe it even supports global npm install (npm -g) without sudo.

**Comment by frink** [comment]
not present for westfield-endpoint-generator in app-endpoint-server/node-modules/.bin

npm is telling the truth...

**Comment by Zubnix** [comment]
Strange stuff. https://docs.npmjs.com/files/folders#executables

I managed to reproduce it briefly as I had the westfield-endpoint-generator globally installed. After uninstalling it, I had the same error. However by removing the node_modules directory and running `npm install` again, it all worked. :disappointed:

**Comment by frink** [comment]
will try that

**Comment by frink** [comment]
Okay that got me over the hump. Not it's complaining about cmake version.
Let me see if I can pull from Debian unstable.

**Comment by Zubnix** [comment]
The cmake version is pretty arbitrary, we can probably lower it and it will probably still work.

**Comment by frink** [comment]
Having problems with cmake. Can't upgrade without making system unstable.
Why do we need CMake > 3.10?

**Comment by frink** [comment]
I'm on stretch and really need to stay there because the kernel is specialized provided by VPS host. Upgrading cmake fources an upgrade of libc6 which forces everything else to upgrade. Highly unstable option. But buster and sid have this porblem so I'm kinda stuck...

**Comment by Zubnix** [comment]
Try downgrading the cmake version, we can probably do with a lower version. you can use `npm link` to point to your local (working) version.

**Comment by frink** [comment]
specified in build file?

My cmake is 3.7.2
your build wants 3.10

**Comment by frink** [comment]
Don't see where to change the version requirement...

**Comment by Zubnix** [comment]
https://github.com/udevbe/westfield/blob/master/server/node/endpoint-native/CMakeLists.txt#L1

**Comment by Zubnix** [comment]
Maybe I'll see if I can release a new Westfield version in the next few days. Some things in Westfield need fixing and changed to make copy-paste work anyway.

**Comment by frink** [comment]
Gotcha. I'll try downgrading the CMake...

**Comment by frink** [comment]
How do I reference my changed westfield from greenfield?

**Comment by Zubnix** [comment]
@frink you can use `npm link <path-to-westfield-native>` inside the application-endpoint-server directory. However it's a transitive dependency so I'm not quite sure how well it'll work.

**Comment by frink** [comment]
transitive?

**Comment by Zubnix** [comment]
@frink I've pushed an update to master, the cmake requirement has now been lowered

**Comment by frink** [comment]
will try it :-D

**Comment by Zubnix** [comment]
@frink did you manage to get it working?
