### ISSUE TITLE
Clipboard doesn't cross over on firefox

### ISSUE THREAD

**Issue by rosensvv** [udevbe/greenfield#101]
#86 Is not fixed for me, I cannot copy outside the browser window and I cannot copy into the browser window from the system clipboard.

**Comment by Zubnix** [comment]
What browser are you using? Do you see anything in the browser logs? What native app are you using inside greenfield and on your client?

Sadly clipboard crossover is notoriously difficult to get right in all cases. I've test on Chrome using gtk3-demo-application & kwrite running on XWayland in greenfield, and gnome-terminal as the native client app.

**Comment by rosensvv** [comment]
I tried on firefox and it didn't work. Now that I read your comment I tried it on Edge and it prompted me to allow reading of the clipboard (which firefox didn't) and it works. So I'm guessing it works on chrome-based browsers but not on firefox :(

**Comment by rosensvv** [comment]
This is likely a fault of firefox, but when the following settings are enabled in about:config :
```
dom.events.asyncClipboard.clipboardItem
dom.events.asyncClipboard.read
```
whenever I try to paste something from greenfield, it only shows [object Promise] as the text that gets pasted. The async clipboard implementation in firefox is still in development?

**Comment by Zubnix** [comment]
I've added a fallback to text selection. Firefox by default only allows writing to the clipboard, so remote app to native client app should work by default. The other way around requires some permissions/features explicitly enabled.

**Comment by Zubnix** [comment]
Is this fixed for you? I believe it's working as well as it can for Firefox?
