### ISSUE TITLE
Can't resolve './api'

### ISSUE THREAD

**Issue by TheAwesome98-Real** [udevbe/greenfield#103]
When I `yarn build`:
```
Compiled with problems:

ERROR in ./src/WebFS.ts 17:0-48

Module not found: Error: Can't resolve './api' in '/path/to/greenfield/compositor-module/src'


ERROR in ./src/RemoteSocket.ts (/path/to/greenfield/compositor-module/src/RemoteSocket.ts) 21:40-47

[tsl] ERROR in /path/to/greenfield/compositor-module/src/RemoteSocket.ts(21,41)
      TS2307: Cannot find module './api' or its corresponding type declarations.


ERROR in ./src/WebFS.ts (/path/to/greenfield/compositor-module/src/WebFS.ts) 18:40-47

[tsl] ERROR in /path/to/greenfield/compositor-module/src/WebFS.ts(18,41)
      TS2307: Cannot find module './api' or its corresponding type declarations.
```

**Comment by Zubnix** [comment]
I can't currently test this but that should be generated automatically. You do need to have java available at build time for this to work, as it uses an open-api code generation tool. You can try generating it explicitly with `yarn generate`.

**Comment by TheAwesome98-Real** [comment]
I’ll try that

**Comment by stellarpower** [comment]
Thanks, that fixed it. I have Java available at build, but presumably the generate step did not get called before `yarn demo`. Perhaps needs to be added to the docs [here](https://github.com/udevbe/greenfield#greenfield-compositor-module) (?)

**Comment by Zubnix** [comment]
Thanks for the info! I've updated the readme.
