### ISSUE TITLE
XWayland support

### ISSUE THREAD

**Issue by Zubnix** [udevbe/greenfield#12]
Adding XWayland support would allow running large number of applications that do not have a Wayland port. For this we need to implement an X window manager in the Greenfield compositor. It  will be required to compile a modified XCB/Xlib to WebAssembly in order to maximize code reuse.

**Comment by Zubnix** [comment]
Inestigate if we can use https://github.com/sidorares/node-x11 in the browser, maybe fork & patch it so it can use websockets and doesn't need node dependencies.

**Comment by sabrehagen** [comment]
The lack of XWayland support seems to be the number one blocker to adopting greenfield. Do you have plans to address this feature in the near term?

**Comment by Zubnix** [comment]
I wasn't really aware this was the number one priority for users. I'm currently doing a rather large refactor of the core middleware using redux-saga + typescript which is almost done. Once finished (hopefully somewhere this week), I could start the XWayland support.

**Comment by sabrehagen** [comment]
I'm making the claim it's "number one" given the majority of Linux graphical applications require X11 to function, thereby the majority of users require X11 support in greenfield to use their daily applications.

Starting work on XWayland would be most exciting. Thanks for taking up the challenge :)

**Comment by Zubnix** [comment]
## TODO

- [ ] X calls over websocket. In progress, see: https://github.com/udevbe/browser-x11
- [ ] X window manager inside greenfield

**Comment by sabrehagen** [comment]
Hello! Just wanted to check in to see how progress on this was going 😃

**Comment by Zubnix** [comment]
DONE:
- The current state is that there is a working pure TypeScript X library: https://github.com/udevbe/xtsb 
- The entire codebase of Greenfield (+Westfield+WebShell) has also been ported to TypeScript.
- I also needed a bit a change of code and build a custom WebGL react renderer, so in the future you could run React apps in Greenfield (think of it as a react-native but for Greenfield): https://github.com/udevbe/react-canvaskit

TODO:
- xtsb connection logic needs to be adapted so it can communicate over websocket
- an XWayland Window Manager needs to be implemented in Greenfield. This is non trivial as it will need to be multi X-server aware, although we can probably start by supporting just a single X-server for now.

**Comment by Zubnix** [comment]
DONE:
- All things XWayland execpt:

TODO
- fullscreen support for XWayland
- copy/paste

**Comment by sabrehagen** [comment]
So great to see this supported! Thank you!!

**Comment by Zubnix** [comment]
c/p is now fully implemented for both xwayland and browser

fullscreen supported will be added later on
