### ISSUE TITLE
Use Flutter-Web as web app widget toolkit

### ISSUE THREAD

**Issue by Zubnix** [udevbe/greenfield#13]
Currently [Flutter Web](https://flutter.dev/web) uses [CSS Houdini](https://developers.google.com/web/updates/2016/05/houdini) as it's paint back-end. For it to be able to run as a Greenfield web-app, we need to implement a custom renderer that can output to an array buffer or offscreen webgl canvas. The best candidate for this is [CanvasKit](https://skia.org/user/modules/canvaskit) which implements [Skia](https://skia.org/) in WebAssembly. The big advantage of this approach being that all mentioned drawing apis are based on the Canvas2D api + we get offscreen webgl acceleration for free.

**Comment by WSLUser** [comment]
Were you able to make any progress with this yet?

**Comment by trusktr** [comment]
What about using Three.js for compositing the windows?

**Comment by Zubnix** [comment]
An intermediate step is to first get plain Skia canvaskit to work. This should be relatively straightforward. An alternative to Flutter might be to create a custom react renderer using skia canvaskit. Not sure which one is less work...

**Comment by Zubnix** [comment]
Custom react renderer using skia on top of webgl: https://github.com/udevbe/react-canvaskit

**Comment by Zubnix** [comment]
No longer relevant at this point
