### ISSUE TITLE
Update Node module to latest code

### ISSUE THREAD

**Issue by shawnco** [udevbe/greenfield#132]
The current Node module (https://www.npmjs.com/package/greenfield-compositor) points to code that doesn't exist anymore. Would it be possible to update it, particularly the frontend portion, to the latest code?

**Comment by Zubnix** [comment]
I'll try to release something this week

**Comment by Zubnix** [comment]
I've released all modules under the @gfld namespace: https://www.npmjs.com/search?q=%40gfld

I haven't thoroughly tested them yet so please report any bugs you may find.

**Comment by Zubnix** [comment]
Let me know if something is missing or not working.
