### ISSUE TITLE
Size allocation issue on all windows when maximizing

### ISSUE THREAD

**Issue by dankasak** [udevbe/greenfield#140]
I have an app I'm running in wayland mode, via compositor-proxy. If I maximize a window, it looks like the size allocation is wrong, and I "lose" the bottom of the window. I can then drag the window up, and see the missing part ( but I lose the top part ). Interestingly, the height of the missing contents is about the same as the heights of the top bar that the compositor-shell renders. Perhaps this height is mistakenly being included when gtk ( 3 in this case ) does its calculation to go into the maximized state?

**Comment by Zubnix** [comment]
I'll see if I can revise the initial size logic, other users reported similar issues.

**Comment by Zubnix** [comment]
I've was able to reproduce and found the issue. Working on a fix.
