### ISSUE TITLE
A question about authentication

### ISSUE THREAD

**Issue by mauvray** [udevbe/greenfield#146]
Hi !
I didn't have time yet to try greenfield but it is on my todolist. I have a question concerning authentification : is there any plan for it ? If yes, how ? Based on remote host ? /etc/password ?

**Comment by Zubnix** [comment]
There's currently only [basic-auth that is configured per remote compositor-proxy-cli](https://greenfield.app/pages/design/#usage-1). More auth options can be added in the future. Which ones or what situation would you like to use them in?
