### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by parsley42** [udevbe/greenfield#2]
Sorry I don't really know much about node applications, so this might be a dumb question. I'm trying to run this remotely, but my connection to port 8080 is always answered with `Cannot GET /` (even if, for instance, I `curl localhost:8080`). Is there an index page that I should be getting but I'm not? I tried looking for `/index.js` and a few others, but no luck.

**Comment by Zubnix** [comment]
Can you copy paste the output of `npm install` and separately `npm start` to https://hastebin.com/ and provide me the link? Perhaps some OS dependencies are missing during installation(?)

**Comment by Zubnix** [comment]
Here's what a successful build looks like: https://pastebin.com/KrHfqh8M
And here when it's started after connecting to `localhost:8080`: https://pastebin.com/B1XrisyV

**Comment by parsley42** [comment]
Here's my build: https://pastebin.com/e0iSvJN0
... and here's npm start:
```
$ npm start

> greenfield-client@1.0.0 start /home/parse/git/greenfield
> node ./local/src/index.js

 --- Loaded configuration: /home/parse/git/greenfield/local/src/DefaultConfig.json ---
{
  "http-server": {
    "port": 8080,
    "socket-timeout": 6000,
    "static-dirs": [
      {
        "http-path": "/apps/icons",
        "fs-path": "./app-entries/"
      }
    ]
  },
  "png-encoder": {
    "max-target-buffer-size": 65536
  },
  "desktop-shell": {
    "apps-controller": {
      "app-entries-urls": [
        "file:./app-entries/"
      ]
    }
  }
}

>>> Running in PRODUCTION mode <<<
```
I haven't scrutinized my build yet for differences from yours. When I connect to 8080, I'm still just getting:
`Cannot GET /`.

Thanks for having a look. BTW, what distro are you using? I'm doing this on AWS instances and can spin up just about anything; right now I'm trying on Amazon Linux 2 with CentOS7 RPMFusion packages.

**Comment by parsley42** [comment]
Oh, also - the `npm start` output is all I ever get; no additional output when I try to connect, just the error in my browser window. I'm just hitting `ctrl-c` to exit.

**Comment by parsley42** [comment]
... Success ! I'll keep working on this for Amazon Linux 2, but on Fedora I found that I needed to install Java for the last part of the build. So I'm getting a page w/ icons on Fedora 28.

**Comment by parsley42** [comment]
Java on Amazon Linux 2 didn't help. I'll keep playing with Fedora.

**Comment by Zubnix** [comment]
Ah yes, the Java part is needed (but actually very much optional really) to minimize the build using google closure compiler. I'll update the build & readme instructions to remediate that.

**Comment by Zubnix** [comment]
I have tested greenfield on Ubuntu, Debian & Gentoo without issue. I'm confused about the error you get. In essence nearly all the web parts are just static files (javascript, html & images) that are served through a simple nodejs express library:
https://github.com/udevbe/greenfield/blob/master/local/src/index.js#L51

Perhaps the relative path resolving does not point to the expected directory on amazon?
You can try adding `console.log(path.join(__dirname, '../../browser/dist'))` before that line to see what it resolves to.
