### ISSUE TITLE
Display tearing on Chromebook

### ISSUE THREAD

**Issue by parsley42** [udevbe/greenfield#45]
The preview app is amazing on my Linux workstation, but looks poor on my chromebook - some kind of sync/refresh rate issue? I couldn't capture it with a screenshot, but you can see it in the picture I took w/ my phone:
https://photos.app.goo.gl/T3naXyT4sTULeGNx9

**Comment by Zubnix** [comment]
I suspect it to be a bug in chrome(os). What actually happens here is that an offscreen webgl canvas is being used a texture source for an onscreen webgl canvas. The tearing/sync should be handled by the browser (web)gl as far as I'm aware.

I noticed other buggy behavior with this where the animation occasionally stutters. Doing some extensive tracing saw no code-wise blockages, which makes me believe the 'offscreen canvas as texture for onscreen canvas' is a badly tested scenario on chrome.
