### ISSUE TITLE
Question about fix_wrtc_native_module_require.patch

### ISSUE THREAD

**Issue by markandrus** [udevbe/greenfield#5]
Hi,

Can you please tell me why [`fix_wrtc_native_module_require.patch`](https://github.com/udevbe/greenfield/blob/master/fix_wrtc_native_module_require.patch) is required? It looks simple enough—perhaps we can land it in node-webrtc (with added support for Debug builds).

Mark

**Comment by Zubnix** [comment]
I has to do with the way https://github.com/zeit/pkg resolves the 'requires' statement. A lot of node native modules use node-cmake to simplify the finding of the native module. However the way node-cmake does it, breaks the final build when using zeit/pkg (as pkg has some kind of internal file system that does not match how node-cmake runtime resolution). Hence I created the patch(es).

**Comment by markandrus** [comment]
Hi, @Zubnix—as of wrtc@0.3.4, released today, I think the patch is no longer needed. The new version supports pkg.
