### ISSUE TITLE
browser vs app context menu 

### ISSUE THREAD

**Issue by jschueller** [udevbe/greenfield#58]
another small issue that appears with apps that have a context menu (on right click) is that the browser context menu interferes as it appears on top of the app menu:
![Screenshot_20210115_104015](https://user-images.githubusercontent.com/3832365/104708940-9aa3e600-571e-11eb-9260-8f02d53fc65f.png)
apparently it can be disabled at the browser level (eg firefox), but maybe the html framework used here has a way of disabling the browser menu

**Comment by Zubnix** [comment]
I pushed a fix that seems to work. Can you confirm it works for you?

**Comment by jschueller** [comment]
It works great! thanks!
