### ISSUE TITLE
greenfield.app/docs leads to 404

### ISSUE THREAD

**Issue by cubuzz** [udevbe/greenfield#62]
The link to the greenfield documentation ( https://greenfield.app/docs/ ) leads into a 404 void.

**Comment by Zubnix** [comment]
Indeed those pointed to the old docs that are outdated/no longer valid and would lead to confusion. Is there anything in particular that you would like to see explained that is not available in this repo?

**Comment by cubuzz** [comment]
I was hoping to find some more detailed install instructions since running those commands alone caused some issues with GSL not loading (iirc, was 2 days ago). Not sure why exactly. That issue is totally on my end, tho, so your code seems to be fine :)
I can still post the errors here, if you want me to ^^

**Comment by Zubnix** [comment]
The installation should be quite simple. You can look at the (debian) dependencies in the dockerfile of the app-endpoint-server to give you an idea of what you might need: https://github.com/udevbe/greenfield/blob/master/app-endpoint-server/Dockerfile#L69

**Comment by cubuzz** [comment]
Thank you, I missed that file. This should allow me to resolve this issue 👍
