### ISSUE TITLE
Trying to launch greenfield browser on Windows machine 

### ISSUE THREAD

**Issue by rmoback** [udevbe/greenfield#80]
Followed the readme with downloading repository and running following command from root. 

`pushd compositor-module && yarn install && yarn build && yarn link && popd && pushd compositor-demo && yarn install && yarn link greenfield-compositor && yarn star` 
and got following errors 

![greenfield](https://user-images.githubusercontent.com/77753827/121439124-edd73900-c94a-11eb-98e7-dbec35013851.PNG)

I am trying to launch greenfield on windows machine and connect with Linux docker image with wayland apps. 
I am new to wayland so please share your thoughts if the Greenfield compositor can be launched on windows or not?

**Comment by Zubnix** [comment]
Greenfield can work on a windows but only if you use wsl2. In fact I did that in the past already: https://github.com/microsoft/WSL/issues/938#issuecomment-560030005
