### ISSUE TITLE
Clipboard works only within remote enviroment

### ISSUE THREAD

**Issue by rosensvv** [udevbe/greenfield#86]
Copy and paste works properly within remote apps but doesn't propagate to the thin client system (can't copy to and from outside the browser tab). Consider this a feature request if it's not a bug as it would be very useful for productivity.

**Comment by Zubnix** [comment]
It's indeed not implemented yet but is currently the # 1 priority and being actively worked on.  I hope to have this working somewhere beginning of next year (Q1 2022), hopefully sooner.
