### ISSUE TITLE
Unable to launch Qt apps on Ubuntu 20.04

### ISSUE THREAD

**Issue by t123yh** [udevbe/greenfield#88]
Hi,

I'm trying to get Qt apps like `konsole` or `kate` to work under Greenfield. Currently, app shows up in browser for a second, but crashes immediately.

```
me@me-server ~ [1]> konsole -platform wayland
Using Wayland-EGL
Using the 'xdg-shell' shell integration
listener function for opcode 5 of wl_pointer is NULL
fish: “konsole -platform wayland” terminated by signal SIGABRT (Abort)
```

**Comment by Zubnix** [comment]
I’ve only tested with kwrite without issues, could you test as well? So I can see if it’s a general qt issue or something else.

**Comment by Zubnix** [comment]
I can't seem to reproduce the issue using ubuntu 21.10.

Can you try running with WAYLAND_DEBUG=1, ie. `WAYLAND_DEBUG=1 konsole -platform wayland`
Could you also show me the log output of the compositor-proxy using ` GST_DEBUG=3 yarn demo`

**Comment by t123yh** [comment]
Hi Zubnix,

Thanks for your reply. I tried `kwrite` and the same happened, so it should be a general qt issue.

These logs below are produced with the options you mentioned.

[kwrite.log](https://github.com/udevbe/greenfield/files/7740192/kwrite.log)

[proxy.log](https://github.com/udevbe/greenfield/files/7740193/proxy.log)

**Comment by Zubnix** [comment]
I see you are running on Mac. This should work but I haven’t tested in a while as I don’t own a Mac. I’ll see if I can reproduce and report back here.

**Comment by t123yh** [comment]
If it will bring any convenience, I can grant you ssh to my server to ease the reproduce of the problem.

**Comment by Zubnix** [comment]
sure, check my github profile for contact details

**Comment by t123yh** [comment]
I am able to launch them on latest Debian. It might be a compatibility issue in 20.04.
