### ISSUE TITLE
hardware acceleration

### ISSUE THREAD

**Issue by Zubnix** [udevbe/greenfield#92]
Currently the native compositor-proxy does not expose any hardware acceleration to clients. This means clients are force to communicate their content using RAM shared memory which is generally slow, especially if we're to upload them to the GPU for video encoding.

TODO:
- Expose hardware acceleration capabilities to clients
- Use shared client EGL Images and feed them directly to the GPU video encoder without copies.

**Comment by rosensvv** [comment]
So which part is hardware accelerated now? How to set it up and test if it's working? What hardware do I need?

**Comment by Zubnix** [comment]
You basically need to check if you have a `/dev/dri/renderD128` and a `/dev/dri/card0` entry. If you have multiple cards there can be addtional `renderD129` and `card1` etc. entries.

You then need to configure the proxy to use the render device of your choosing: https://github.com/udevbe/greenfield/blob/master/compositor-proxy/src/config.yaml#L13

This allows applications to utilize the GPU to do their rendering (e.g. GTK4, XWayland) and should give you a modest but noticeable speed improvement (depending if the client application uses software or hardware accelerated rendering).

The real speed improvement will come once https://github.com/udevbe/greenfield/issues/104 lands. (First tests shows a ±2.5x increase in FPS)
